### ISSUE TITLE
Untrack all dispatch operations

### ISSUE THREAD

**Issue by alxhub** [reduxjs/angular-redux#18]
The read of `selectedState` [here](https://github.com/reduxjs/angular-redux/blob/ba4f0c0e2db6d5035273b7548d8f2a8b1704a23d/projects/angular-redux/src/lib/inject-selector.ts#L98) can end up tracked in a reactive context like an `effect`, if a dispatch is made inside of that context. This happens because a dispatch causes subscribers to run synchronously to receive the newly reduced state, and `selectedState` is read inside a subscriber.

There are 2 possible fixes here:

1. For good reactive hygiene, ideally the whole`dispatch()` operation should be untracked. Nothing downstream of `dispatch()` makes sense to track if invoked from a reactive context.

2. In addition to 1, `linkedSignal` supports equality directly so the read of `selectedState` in order to invoke the equality function is actually not necessary. Instead, the equality operation can be delegated to `linkedSignal`.

**Comment by crutchcorn** [comment]
This is causing issues in a minimal repro I made here:

https://stackblitz.com/edit/stackblitz-starters-3iluayah?file=src%2Fmain.ts
